listen 8080;
access_log /srv/apps/drop/logs/access.log;
error_log /srv/apps/drop/logs/error.log;

location @drop_app {
    proxy_pass http://unix:/tmp/drop.sock;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
}

location /~static/ {
    alias /srv/apps/drop/~static/;
}

location / {
    try_files $uri @drop_app;
    if ($request_method = OPTIONS) {
        return 204;
    }
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Max-Age 3600;
    add_header Access-Control-Expose-Headers Content-Length;
    add_header Access-Control-Allow-Headers Range;
}
