access_log /srv/apps/drop/logs/access.log;
error_log /srv/apps/drop/logs/error.log;

location @drop_app {
    proxy_pass http://unix:/tmp/drop.sock;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
}

location /~static/ {
    alias /srv/apps/drop/~static;
}

location / {
    try_files $uri @drop_app;
}

include /etc/nginx/letsencrypt-serv.conf;
