server {
    server_name ~^drop\.bakatrouble\.(pw|me)$;
    root /srv/apps/drop/files;

    include /srv/apps/drop/configs/nginx_include.conf;
}

server {
    server_name ~^(?<dir>.*)\.drop\.bakatrouble\.(pw|me)$;
    root /srv/apps/drop/subdomain_files/$dir;

    include /srv/apps/drop/configs/nginx_include.conf;
}

server {
    if ($host ~ ^(.*\.)?drop\.bakatrouble\.(pw|me)$) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name ~^(.*\.)?drop\.bakatrouble\.(pw|me)$;
    return 404;
}