server {
    server_name ~^drop\.bakatrouble\.me$;
    root /srv/apps/drop/files;

    include /srv/apps/drop/configs/nginx_include.conf;
}

server {
    server_name ~^(?<dir>.*)\.drop\.bakatrouble\.me$;
    root /srv/apps/drop/subdomain_files/$dir;

    include /srv/apps/drop/configs/nginx_include.conf;
}