[program:drop]
user = arch
directory = /srv/apps/drop
command = /srv/apps/drop/venv/bin/python /srv/apps/drop/autoindex.py
autostart = true
autorestart = true
stderr_logfile = /srv/apps/drop/logs/app.log
stdout_logfile = /srv/apps/drop/logs/app.log
stopsignal = INT
environment = ENV=PRODUCTION
